SOURCE: CT
TARGET: MR
NUM_WORKERS: 4
FULLY_SUPERVISED: False
TRAIN:
  MAX_ITERS: 5000
  DA_METHOD: baseline
  MODEL:     DeepLabv2
  RESTORE_FROM: ../pretrain_model/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL:     True
  LAMBDA_DICE_SRC_MAIN: 1.0
  LAMBDA_DICE_SRC_AUX:  0.1
TEST:
  MODE: best